# StateFlow examples

<!--- INCLUDE .*
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.*
import kotlinx.coroutines.test.*
import kotlin.coroutines.cancellation.CancellationException
-->

<!--- TEST_NAME CoroutineExceptionHandlerTest -->

## CancellationException ReThrowTest

```kotlin

fun main() {
    val scope =
        CoroutineScope(SupervisorJob() + Dispatchers.IO + CoroutineExceptionHandler { coroutineContext, throwable ->
            println("CoroutineExceptionHandler")
        })
    scope.launch {
        runCatching {
            println("start")
            delay(1000)
        }.onFailure {
            if (it is CancellationException) throw it
            println("on fail")
        }
    }
    Thread.sleep(300)
    println("cancel")
    scope.cancel()
    Thread.sleep(300)
}
```

> You can get the full code [here](../src/test/java/samples/example-coroutines-01.kt).

```text
start
cancel
```

<!--- TEST -->


## CancellationException NoReThrowTest

```kotlin

fun main() {
    val scope =
        CoroutineScope(SupervisorJob() + Dispatchers.IO + CoroutineExceptionHandler { coroutineContext, throwable ->
            println("CoroutineExceptionHandler")
        })
    scope.launch {
        runCatching {
            println("start")
            delay(1000)
        }.onFailure {
            println("on fail")
        }
    }
    Thread.sleep(300)
    println("cancel")
    scope.cancel()
    Thread.sleep(300)
}
```

> You can get the full code [here](../src/test/java/samples/example-coroutines-02.kt).

```text
start
cancel
on fail
```

<!--- TEST -->


## CancellationException NoReThrowTest and Specify exception handler

```kotlin

fun main() {
    val scope =
        CoroutineScope(SupervisorJob() + Dispatchers.IO)
    scope.launch(CoroutineExceptionHandler { coroutineContext, throwable ->
        println("CoroutineExceptionHandler")
    }) {
        runCatching {
            println("start")
            delay(1000)
        }.onFailure {
            if (it is CancellationException) throw it
            println("on fail")
        }
    }
    Thread.sleep(300)
    println("cancel")
    scope.cancel()
    Thread.sleep(300)
}
```

> You can get the full code [here](../src/test/java/samples/example-coroutines-03.kt).

```text
start
cancel
```

<!--- TEST -->

## Not CancellationException and throw CancellationException manually

```kotlin

 fun main() {
    val scope =
        CoroutineScope(SupervisorJob() + Dispatchers.IO + CoroutineExceptionHandler { coroutineContext, throwable ->
            println("CoroutineExceptionHandler")
        })
    scope.launch {
        println("launch")
        throw RuntimeException()
    }
    Thread.sleep(300)
}
```

> You can get the full code [here](../src/test/java/samples/example-coroutines-04.kt).

```text
launch
CoroutineExceptionHandler
```

<!--- TEST -->
